### ISSUE TITLE
Update to ESP-IDF 3.3.2 or 4.0

### ISSUE THREAD

**Issue by amotl** [pycom/pycom-esp-idf#20]
Dear Pycom team,

Espressif released ESP-IDF 3.3.2 on April 9, 2020 [1]. May I humbly ask if you are already working on bringing these updates to the Pycom firmware ecosystem? I believe there are many improvements from which Pycom MicroPython might also benefit from.

With kind regards,
Andreas.

[1] https://github.com/espressif/esp-idf/releases/tag/v3.3.2

cc @Xykon, @husigeza, @geza-pycom, @catalinio, @doniks, @peter-pycom

**Comment by catalinio** [comment]
Hi Andreas,

We are already in advanced stage with IDF 4.0 update, still a few modules to be ported (due to API updates).
Actually, we already released Pymesh BLE engineering images, exposing BLE Mesh, on idf 4.0, with limited functionality. 
After we'll release official development on idf v4.0 (and receive feedback), we can look into v3.3.2 if we should still update.

Thanks,
Catalin

**Comment by amotl** [comment]
Dear Catalin,

thanks for the interesting insights. Upgrading to ESP-IDF 4.x will be even better. Is there anything you can already get into the hands of the community regarding your current work?

With kind regards,
Andreas.

P.S.: A little bit OT, but: When moving on to ESP-IDF 4.x, can we expect that you will also pull in respective changes from MicroPython 1.12, on which this might be based upon?

**Comment by amotl** [comment]
> Upgrading to ESP-IDF 4.x will be even better.

I just found that @geza-pycom has been working on that within [1] ff. Thanks a bunch and keep up the spirit!

[1] https://github.com/geza-pycom/pycom-esp-idf/commits/idf_v4.0

**Comment by geza-pycom** [comment]
That branch in my personal repository is really outdated so I removed it to avoid confusion.

**Comment by amotl** [comment]
Dear Géza (@geza-pycom),

ok, thanks! Please let us know when there will be something to pick up on this matter.

Stay safe and with kind regards,
Andreas.
